server:
  port: 8083
spring:
  application:
    name: eureka-client-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:
    enabled: true

eureka-client-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule